Red Cell Foundation/donors/urls.py
from django.urls import path
from donors.views import DonorDetailView, DonorListView, DonorCreateView, DonorRegThanksView

app_name = 'donors'

urlpatterns = [
    path('', DonorListView.as_view(), name="donor-list"),
    path('<int:pk>', DonorDetailView.as_view(), name="donor-detail"),
    path('new', DonorCreateView.as_view(), name="donor-create"),
    path('thanks', DonorRegThanksView.as_view(), name="thanks"),
    path('<blood_group>', DonorListView.as_view(), name="search-donor")
]

Red Cell Foundation/hackout/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('donors/logout',
         views.LogoutView.as_view(next_page='hospitals:index'), name="donor_logout"),
    path('', include("hospitals.urls", namespace="hospitals")),
    path('donors/', include("donors.urls", namespace="donors"),),
    path('donors/login/', views.LoginView.as_view(template_name="donors/login.html",
                                                  redirect_field_name='hospital:donor-detail pk=donor.pk'), name="donor_login"),

]

Red Cell Foundation/hospitals/urls.py
from django.urls import path
from hospitals.views import HospitalDetailView, HospitalCreateView, EntryCreateView, EntrySuccessView, EntryUpdateView, EntryDeleteView, SearchView, EntryListView, HospitalView

app_name = "hospitals"

urlpatterns = [
    path('', SearchView.as_view(), name="index"),
    path('hospitals-final', HospitalView, name="hospital-list-final"),
    path('<blood_group>', EntryListView.as_view(), name="search"),
    #   path('hospitals', HospitalListView.as_view(
    #      template_name="hospital_list.html"), name="hospital-list"),
    path('hospital/<int:pk>', HospitalDetailView.as_view(), name="hospital-detail"),
    path('hospital/new', HospitalCreateView.as_view(), name="hospital-create"),
    path('entry/new', EntryCreateView.as_view(), name="entry-create"),
    path("entry_success", EntrySuccessView.as_view(), name="entry-success"),
    path("entry/<int:pk>/update", EntryUpdateView.as_view(), name="entry-update"),
    path("entry/<int:pk>/delete", EntryDeleteView.as_view(), name="entry-delete")
]

Red Cell Foundation/donors/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Donor(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    blood_group = models.CharField(max_length=5)
    phone = models.BigIntegerField()
    city = models.CharField(max_length=300)
    longitude = models.FloatField(default=0.0)
    latitude = models.FloatField(default=0.0)

    def __str__(self):
        name = f"{self.user.first_name} {self.user.last_name} - {self.blood_group}"
        return name

    def get_absolute_url(self):
        return reverse("donor-detail", kwargs={"pk": self.pk})

Red Cell Foundation/donors/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

BLOOD_GROUPS = (
    ("A+", "A+"),
    ("A-", "A-"),
    ("AB+", "AB+"),
    ("AB-", "AB-"),
    ("B+", "B+"),
    ("B-", "B-"),
    ("O+", "O+"),
    ("O-", "O-"),
)


class DonorForm(UserCreationForm):
    blood_group = forms.ChoiceField(choices=BLOOD_GROUPS)
    phone = forms.IntegerField()
    city = forms.CharField()
    longitude = forms.FloatField()
    latitude = forms.FloatField()

    class Meta:
        model = User
        fields = ['username', 'password1', 'password2',
                  'first_name', 'last_name', 'phone', 'blood_group', ]

Red Cell Foundation/donors/views.py
from django.shortcuts import render
from django.views.generic import DetailView, ListView, CreateView, FormView, TemplateView
from django.contrib.auth.models import User
from donors.models import Donor
from donors.forms import DonorForm
from django.contrib.auth.mixins import LoginRequiredMixin


class DonorDetailView(DetailView, LoginRequiredMixin):
    model = Donor
    template_name = "donors/donor_detail.html"


class DonorListView(ListView):
    template_name = "donors/donor_list.html"

    def get_queryset(self):
        return Donor.objects.filter(blood_group=self.kwargs['blood_group'])


class DonorRegThanksView(TemplateView):
    template_name = "donors/donor_create_success.html"


class DonorCreateView(FormView):
    model = User
    form_class = DonorForm
    success_url = 'thanks'
    template_name = 'donors/donor_create.html'

    def form_valid(self, form):
        phone = form.cleaned_data['phone']
        blood_group = form.cleaned_data['blood_group']
        city = form.cleaned_data['city']
        longitude = form.cleaned_data['longitude']
        latitude = form.cleaned_data['latitude']
        new_user = form.save()
        d = Donor(user=new_user, blood_group=blood_group,
                  city=city, phone=phone, longitude=longitude, latitude=latitude)
        d.save()
        return super().form_valid(form)

Red Cell Foundation/donors/templates/donors/base.html
{% load static from staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'index.css' %}">
    <title>The RedCell Foundation</title>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark text-light sticky-top" style="background-color: #EA2027; color: #ecf0f1;">
  <a class="navbar-brand" href="{% url 'hospitals:index' %}">The RedCell Foundation</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="#">About Us</a>
      </li>
    </ul>

    <ul class="navbar-nav ml-auto">
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a href="{% url 'hospitals:hospital-list-final' %}" class="nav-link">Hospitals</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'donors:donor-detail' pk=user.pk %}" class="nav-link">Profile</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'donor_logout' %}" class="nav-link">Logout</a>
        </li>
        <li class="nav-item">
          <a href="#" class="nav-link">@{{request.user.username}}</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a href="{% url 'donor_login' %}" class="nav-link btn btn-dark btn-sm nav-item mx-2 active">Login</a>
        </li>
        <li class="nav-item">
          <a href="{% url 'donors:donor-create' %}" class="nav-link">Register</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

    <div class="container1">
        {% block content %}
        {% endblock content %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

Red Cell Foundation/donors/templates/donors/donor_create.html
{% extends 'donors/base.html' %}
{% block content %}
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <div class="container3">
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button onclick="getLocation()", class="btn btn-info" id="getLocationBtn">Get Location</button>
            <button type="submit" value="Submit" class="btn btn-lg my-3 btn-dark mx-5">Submit</button>
        </form>
    </div>
    <script>
    latitude = document.getElementById("id_latitude");
    longitude = document.getElementById("id_longitude");
    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else { 
            console.log("Geolocation is not supported by this browser.");
        }
    }

    function showPosition(position){
        latitude.setAttribute("value",position.coords.latitude);
        longitude.setAttribute("value",position.coords.longitude);
        latitude.style.display = 'none';
        longitude.style.display = 'none';
        document.getElementById("getLocationBtn").style.display = 'none';
        $('label[for="id_longitude"]').hide ();
        $('label[for="id_latitude"]').hide ();
    }

    window.onload = getLocation();
    </script>
{% endblock content %}

Red Cell Foundation/donors/templates/donors/donor_create_success.html
{% extends 'donors/base.html' %}
{% block content %}
    <center><h1>Thanks for registering</h1></center>
{% endblock content %}

Red Cell Foundation/donors/templates/donors/donor_detail.html
{% extends 'donors/base.html' %}
{% block content %}
    <div class="jumbotron">
        <h2>{{donor.user.first_name}} {{donor.user.last_name}}</h3>
        <h4>Blood Group: {{donor.blood_group}}</h4>
        <h4>Phone: {{donor.phone}}</h4>
        <h4>Location: {{donor.location}}</h4>
    </div>
{% endblock content %}

Red Cell Foundation/donors/templates/donors/donor_list.html
{% extends 'donors/base.html' %}
{% block content %}
    <br>
    <div class="pt-4 px-5 card mx-auto" style="max-width: 68%;">
        {% for donor in donor_list %}
            <h3 id="name1"><a href="{% url 'donors:donor-detail' pk=donor.pk %}" style="color: rgb(53, 46, 46)">{{donor.user.first_name}} {{donor.user.last_name}}</a></h3>
            <h4>{{donor.blood_group}}</h4>
            <br>
            <hr>
        {% endfor %}
    </div>
{% endblock content %}

Red Cell Foundation/donors/templates/donors/login.html
{% extends 'donors/base.html' %}
{% block content %}
    <div class="background1">
         <form method="post">
        {% csrf_token %}
        <div class="container4">
            <h1 class="text-center my-4">Sign In</h1>
            {{form.as_p}}
            <input type="submit" value="Login" class="btn btn-primary">
        </div>
        </form>
    </div>
   
{% endblock content %}