Red Cell Foundation/donors/urls.py
from django.urls import path
from donors.views import DonorDetailView, DonorListView, DonorCreateView, DonorRegThanksView

app_name = 'donors'

urlpatterns = [
    path('', DonorListView.as_view(), name="donor-list"),
    path('<int:pk>', DonorDetailView.as_view(), name="donor-detail"),
    path('new', DonorCreateView.as_view(), name="donor-create"),
    path('thanks', DonorRegThanksView.as_view(), name="thanks"),
    path('<blood_group>', DonorListView.as_view(), name="search-donor")
]

Red Cell Foundation/hackout/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('donors/logout',
         views.LogoutView.as_view(next_page='hospitals:index'), name="donor_logout"),
    path('', include("hospitals.urls", namespace="hospitals")),
    path('donors/', include("donors.urls", namespace="donors"),),
    path('donors/login/', views.LoginView.as_view(template_name="donors/login.html",
                                                  redirect_field_name='hospital:donor-detail pk=donor.pk'), name="donor_login"),

]

Red Cell Foundation/hospitals/urls.py
from django.urls import path
from hospitals.views import HospitalDetailView, HospitalCreateView, EntryCreateView, EntrySuccessView, EntryUpdateView, EntryDeleteView, SearchView, EntryListView, HospitalView

app_name = "hospitals"

urlpatterns = [
    path('', SearchView.as_view(), name="index"),
    path('hospitals-final', HospitalView, name="hospital-list-final"),
    path('<blood_group>', EntryListView.as_view(), name="search"),
    #   path('hospitals', HospitalListView.as_view(
    #      template_name="hospital_list.html"), name="hospital-list"),
    path('hospital/<int:pk>', HospitalDetailView.as_view(), name="hospital-detail"),
    path('hospital/new', HospitalCreateView.as_view(), name="hospital-create"),
    path('entry/new', EntryCreateView.as_view(), name="entry-create"),
    path("entry_success", EntrySuccessView.as_view(), name="entry-success"),
    path("entry/<int:pk>/update", EntryUpdateView.as_view(), name="entry-update"),
    path("entry/<int:pk>/delete", EntryDeleteView.as_view(), name="entry-delete")
]

Red Cell Foundation/hospitals/models.py
from django.db import models
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.urls import reverse


class Hospital(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, default=1, related_name="hospital")
    name = models.CharField(max_length=256)
    address = models.CharField(max_length=256)
    city = models.CharField(max_length=300)
    longitude = models.FloatField(default=0.0)
    latitude = models.FloatField(default=0.0)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("hospitals:hospital-detail", kwargs={"pk": self.pk})


class Entry(models.Model):
    blood_group = models.CharField(max_length=256)
    hospital = models.ForeignKey(
        Hospital, on_delete=models.CASCADE, related_name="entry")
    quantity = models.IntegerField()

    def __str__(self):
        return f"{self.hospital} - {self.blood_group}"

    def get_absolute_url(self):
        return reverse_lazy("hospitals:hospital-detail", kwargs={"pk": self.hospital.pk})

Red Cell Foundation/hospitals/forms.py
from django import forms
from hospitals.models import Hospital

BLOOD_GROUPS = (
    ("A+", "A+"),
    ("A-", "A-"),
    ("AB+", "AB+"),
    ("AB-", "AB-"),
    ("B+", "B+"),
    ("B-", "B-"),
    ("O+", "O+"),
    ("O-", "O-"),
)


class SearchForm(forms.Form):
    blood_group_input = forms.ChoiceField(choices=BLOOD_GROUPS)
    longitude = forms.FloatField(widget=forms.HiddenInput())
    latitude = forms.FloatField(widget=forms.HiddenInput())

Red Cell Foundation/hospitals/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from hospitals.models import Hospital, Entry
from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView, DeleteView, FormView
from django.urls import reverse_lazy, reverse
from hospitals.forms import SearchForm
from django.contrib.auth.mixins import LoginRequiredMixin


class SearchView(FormView):
    form_class = SearchForm
    template_name = "hospitals/index.html"

    def form_valid(self, form):
        self.form = form
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        bg = self.form.cleaned_data['blood_group_input']
        longitude = self.form.cleaned_data['longitude']
        latitude = self.form.cleaned_data['latitude']
        return reverse('hospitals:search', kwargs={'blood_group': bg})


class EntryListView(ListView):
    template_name = "hospitals/entry_list.html"

    def get_queryset(self):
        return Entry.objects.filter(blood_group=self.kwargs['blood_group'])


class HospitalDetailView(DetailView):
    login_url = 'donor_login'
    model = Hospital
    template_name = "hospitals/hospital_detail.html"


class HospitalCreateView(CreateView):
    model = Hospital
    fields = ['name', 'address', 'city', 'latitude', 'longitude']
    template_name = "hospitals/hospital_create.html"

    def form_valid(self, form):
        this_name = form.cleaned_data['name']
        this_address = form.cleaned_data['address']
        this_city = form.cleaned_data['city']
        this_longitude = form.cleaned_data['longitude']
        this_latitude = form.cleaned_data['latitude']
        current_user = self.request.user
        h = Hospital(user=current_user, name=this_name,
                     address=this_address, city=this_city, longitude=this_longitude, latitude=this_latitude)
        h.save()
        return HttpResponseRedirect(reverse("hospitals:hospital-list-final"))


class EntryCreateView(LoginRequiredMixin, CreateView):
    login_url = 'donor_login'
    model = Entry
    fields = ['blood_group', 'hospital', 'quantity']
    template_name = "hospitals/entry_create.html"


class EntrySuccessView(TemplateView):
    template_name = "hospitals/entry_created.html"


class EntryUpdateView(LoginRequiredMixin, UpdateView):
    login_url = 'donor_login'
    model = Entry
    template_name = "hospitals/entry_update.html"
    fields = ['quantity']


class EntryDeleteView(LoginRequiredMixin, DeleteView):
    login_url = 'donor_login'
    model = Entry
    template_name = "hospitals/entry_delete.html"

    def get_success_url(self):
        return reverse_lazy('hospitals:hospital-detail', kwargs={'pk': self.object.hospital.pk})


def HospitalView(request):
    current_user = request.user
    hospitals = Hospital.objects.filter(user=current_user)
    return render(request, "hospitals/new.html", context={"hospitals": hospitals})

Red Cell Foundation/hospitals/templates/hospitals/entry_create.html
{% extends 'donors/base.html' %}
{% load static from staticfiles %}

{% block content %}
<div class="back1 col-xs-1 center-block">
    <div class="myform">
        <center>
            <h1 class="text-center my-4">Entry</h1>
            <form  method="post">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Submit</button>
            </form>
        </center>
    </div> 
</div>
{% endblock content %}  

Red Cell Foundation/hospitals/templates/hospitals/entry_created.html
{% extends 'donors/base.html' %}
{% block content %}
    <center><h1>The entry has been successfully created</h1></center>
{% endblock content %}

Red Cell Foundation/hospitals/templates/hospitals/entry_delete.html
{% extends 'donors/base.html' %}
{% block content %}
    <form  method="post">
        {% csrf_token %}
        <center>
            <h2 class="mt-5">Are You Sure You want to delete the entry?</p>
            <input type="submit" value="Confirm" class="btn btn-dark btn-lg nav-item mx-2 active">
        </center>
    </form>
{% endblock content %}

Red Cell Foundation/hospitals/templates/hospitals/entry_list.html
{% extends 'donors/base.html' %}
{% block content %}
<a href="{% url 'donors:search-donor' blood_group=view.kwargs.blood_group %}" class="btn btn-primary my-4 ml-5">Search for Donors instead</a>
<div class="jumbotron my-4 mx-5">
    {% for entry in entry_list %}
        <h2>{{entry.hospital.name}}</h2>
        <h3>{{entry.blood_group}}</h3>
        <h3>{{entry.quantity}} Bags</h3>
    {% endfor %}
</div>
{% endblock content %}

Red Cell Foundation/hospitals/templates/hospitals/entry_update.html
{% extends 'donors/base.html' %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Update" class="btn btn-dark btn-lg nav-item mx-2 active">
    </form>
{% endblock content %}

Red Cell Foundation/hospitals/templates/hospitals/hospital_create.html
{% extends 'donors/base.html' %}
{% block content %}
    <script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>
    <div class="body1">
        <div class="mycontainer">
            <center>
                <form  method="post" style="max-width: 90px; padding-top: 3em;">
                    <h1 class="text-center">Entry</h1>
                    <div class="mb-3 mx-automargin">
                        {% csrf_token %}
                        <center>{{form.as_p}}</center>
                    </div>
                    <button onclick="getLocation()", class="btn btn-info" id="getLocationBtn">Get Location</button>
                    <button type="submit" value="Submit" class="btn btn-md my-3 btn-dark mx-5">Submit</button>
                </form>
            </center>
        </div>
    </div>


    <script>
    latitude = document.getElementById("id_latitude");
    longitude = document.getElementById("id_longitude");
    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else { 
            console.log("Geolocation is not supported by this browser.");
        }
    }

    function showPosition(position){
        latitude.setAttribute("value",position.coords.latitude);
        longitude.setAttribute("value",position.coords.longitude);
        latitude.style.display = 'none';
        longitude.style.display = 'none';
        document.getElementById("getLocationBtn").style.display = 'none';
        $('label[for="id_longitude"]').hide ();
        $('label[for="id_latitude"]').hide ();
    }
    window.onload = getLocation();
    </script>
{% endblock content %}

Red Cell Foundation/hospitals/templates/hospitals/hospital_detail.html
{% extends 'donors/base.html' %}
{% block content %}
    <div class="jumbotron pl-5">
        <h1 class="pl-5">{{hospital.name}}</h1>
        <h3 class="pl-5">{{hospital.address}}</h2>
        <hr class="pl-5">

        <h3 class="pl-5">Blood Bank Details</h2>
        {% for entry in hospital.entry.all %}
            <h2 class="pl-5">{{entry}} - {{entry.quantity}} bags</h2>
            <a href="{% url 'hospitals:entry-delete' pk=entry.pk %}" class='btn btn-danger ml-5'>Delete</a><hr>
        {% endfor %}
    </div>
    <center><a href="{% url 'hospitals:entry-create' %}" class='btn btn-primary'>Add New Entry</a></center>
    
{% endblock content %}

Red Cell Foundation/hospitals/templates/hospitals/hospital_list.html
{% extends 'donors/base.html' %}
{% block content %}
    <h1>List of hospitals</h1>
        {% for hospital in hospital_list %}
            <h2><a href="{% url 'hospitals:hospital-detail' pk=hospital.pk %}">{{hospital.name}}</h2></a>
            <h3>{{hospital.address}}</h3>
            <h4>{{hospital.location}}</h4>
            <hr>
        {% endfor %}
{% endblock content %}

Red Cell Foundation/hospitals/templates/hospitals/hospital_list2.html
{% extends 'donors/base.html' %}
{% block content %}
    <h1></h1>
    {% for hospital in object_list %}
        <h1>{{hospital.name}}</h1>
    {% endfor %}
{% endblock content %}

Red Cell Foundation/hospitals/templates/hospitals/index.html
{% extends 'donors/base.html' %}
{% load static from staticfiles %}
{% block content %}
    <!-- Request Blood -->
    <div class="request text-center pt-5">
        <form method="post">
        {% csrf_token %}
        <center>
            <div class="input-group mb-1 mx-auto" style="max-width: 20%;">
                <div class="input-group-prepend">
                    <label for="id_blood_group_input" class="input-group-text" style="font-size: 1.3em;">Blood group input:</label> 
                </div>
                <center>
                    <select name="blood_group_input" id="id_blood_group_input" class="custom-select" style="height: 100%; padding:1em;">
                    <option value="A+">A+</option>
                    <option value="A-">A-</option>
                    <option value="AB+">AB+</option>
                    <option value="AB-">AB-</option>
                    <option value="B+">B+</option>
                    <option value="B-">B-</option>
                    <option value="O+">O+</option>
                    <option value="O-">O-</option>
                </select>
                </center>
                
                <input type="hidden" name="longitude" id="id_longitude"><input type="hidden" name="latitude" id="id_latitude">
            </div>
        </center>
            <input type="submit" value="Search" class="btn btn-light border-danger mx-2 btn-lg">
        </form>
    </div>

    <!-- our supporters -->
    <div class="card supporters text-center" style="width: 100%">
        <div class="card-body">
            <h1 class="headingSupporters">Our Supporters</h1>
            <div class="row">
                <div class="col-md-1"></div>
                <img src="{% static 'Digital_India_empower_youth.jpg' %}" alt="Digital_India_empower_youth" class="col-md-4 col-sm-6">
                <img src="{% static 'logo-who.jpg' %}" alt="WHO" class="col-md-6 col-sm-6">
                <img src="{% static 'billandmalindagates.png' %}" class="col-md-4 col-sm-6 mx-auto" alt="bill and malinda gates foundation">
            </div>
        </div>
    </div>

    <div class="card text-center mb-5" id="motto" style="width: 100%;">
        <div class="card-body">
            <h1 class="card-title my-5">Our Motto</h1>
            <div class="container">
                <p class="card-text mb-5">Our motto is to decrease the death rate due to unavailability of blood when needed by using best in class technologies. We are devoted towards achieving better future in healthcare sector using trusted and compassionate care. We want to grow ourselves in a healthy way which will provide us better result focused solutions via help of client feedback. We believe in proving ourselves as chosen for excellence.</p>
            </div>
        </div>
    </div>

    <!--footer-->
    <div class="footer">
        <div class="container">
            <div class="row text-center pt-3">
                <div class="col-md-4 col-sm-12">
                    <p><a href="#"><b> Utility</b>
                        </a></p>
                    <p><a href="#">Login</a></p>
                    <p><a href="#">Register</a></p>
                </div>
                <div class="col-md-4 col-sm-12">
                    <p><a href="#"><b>About</b>
                        </a></p>
                    <p><a href="#">DA_devs</a></p>
                    <p><a href="contactUs.html">Contact Us</a></p>
                    <p><a href="feedback.html">Feedback</a></p>
                </div>
                <div class="col-md-4 col-sm-12">
                    <p><a href="#"><b>Terms & Condition</b>
                        </a></p>
                    <p><a href="#">Terms of Use</a></p>
                    <p><a href="#">Privacy Policy</a></p>
                    <p><a href="#">Service Policy</a></p>
                </div>
            </div>
            <div class="container ml-auto py-3 text-center">
                <p>&copy; All rights reserved by DA_devs - 2019</p>
            </div>
        </div>
    </div>

    <script>
    latitude = document.getElementById("id_latitude");
    longitude = document.getElementById("id_longitude");
    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(showPosition);
        } else { 
            console.log("Geolocation is not supported by this browser.");
        }
    }

    function showPosition(position){
        latitude.setAttribute("value",position.coords.latitude);
        longitude.setAttribute("value",position.coords.longitude);
        console.log(latitude.value);
        console.log(longitude.value);
    }
    window.onload = getLocation();
    </script>
{% endblock content %}

Red Cell Foundation/hospitals/templates/hospitals/new.html
{% extends 'donors/base.html' %}
{% block content %}
    <div id="mydiv1">
        {% for hospital in hospitals %}
            <h2><a href="{% url 'hospitals:hospital-detail' pk=hospital.pk %}" style="color:black;">{{hospital.name}}</a></h2>
        {% endfor %}
    </div>
    <center>
        <a href="{% url 'hospitals:hospital-create' %}" class="btn btn-lg btn-primary">Create New Hospital</a>
    </center>
{% endblock content %}